language: scala
scala: 2.12.10
jdk: openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "jiwpNfX5VPJnK1qkTJEBtG92qUzMPT9MLioXLwgD+1DLbXJJx8NXZN4PeSpSJ1vjoEEIbxAe5FhQLW777dw6cbDt8T7CCleEf96in5GWmLjnWXehXu7WZSYzdxdYwW0fEGkAPp3G7s3GyAbXXBOEDwkFdAR8nGqeptmBdMUbBkD0MZH3D+m6meE8D0o7IHj+vy8ZCCSCnszRuJVZX8QReQOacvXPpWAdDoo6eQFAj3jNstB+RArflZvs3lX5iR5lNmgiYdipmI8mevOSga00nxHjkKCZwfbqb0hw4Oupl2S0tsLdzwgT4xb88vWDeskaVC4vVRPiV9mrg+YMxd80AI7DaJ0S9qZ9aRuxeS3SB6AiMxv+NYEcNdF27WSMTOy1LRcpKxBe3HSMKtqtxEqWduYzQgnziFkQ5gjLQy9zhcYYcLftgZ3X+ShzPqc7al+gz0RVOP145QdH4p8OtsHGA1R4HLSQ0oS06WJB7M7LYKpAqwtu4ngH5wDqz6RVem8u0bS2vmkB3pIzFcA0mZVBwnN8jwdSL8qdExUk/0Bl7PioO2wQcxVCEHKBucGv23UlAUlGKslK4/4858/5s7naXoEHKZTiiCNI92fbPA7IiXCN7iw1Q5I+DdJrBMNblcl/EDXN33a5GbdZfSJvZhJiXDZiyZjXGK0XDQznAFws8SY="
    # GITHUB_TOKEN
    - secure: "cCpapFMYpajFRbc3YnEDYwpDcMddjAxe+J0p34Vg3qmPeNnrITQKqrCOTOrM9c7lEKX4EldstdleEhDipgNIwW22+hwEMQ8jhe1PyUcxn3z/LLKJFoVhJPn3FHip8C25AwxOKBkRXnVyJgwDmyhYtZwlzFHw944hpROuUkbZV9Vi5cqjzkXXO20XLyp6zjBzcJsNLxe2r/DOgsk1vGwVThD+0SuapvNQyYgZRTWS1hgrGk91V/SRvlkUp+rViPfUlIW3vZD7QXcIR2Emp8FSDgStR5iSwsjbi2iklmWyNes57HavFYWfbgdjOXgbjxdmcG5i749wguDHr0MI2AWShA4qfB4aDPIyIccEb2gPnUnswLxTtmqWHnR1KGG4BGhu/p6+4xeWgnFFhCFNEp+6AlOVMA0E+vhOnZcsWcSakvPrUg+F38jmSR7EueYvpnjabBriCAzoul0tYVcQMMKNP6xynvo1JyWHDITIOE/famyJYssCb2RuFHtg+DtgQhQio2+IAlez2FqsHFJX1o39RF7U3QziTXAMPjt1fDirZGPY5P8euWPdPXMFKPyqO0EPdkWKymYIO8ssUpEuieiWK2g/S55hv0Uii8H4MrjPSAvegsavrXM3H1qSnQME5ttY1dW75HWyJJcJZVh69QCOxdxkh02I2dUEccbVQJo8IiY="
    # GITHUB_ACCESS_TOKEN
    - secure: "r98FsNcWL+yyUTLVnnEbL7rSu9zRshHpog1SinaZd9x9tOWA6fbjTJguWJwpd+HEUts/QFtkGzIOldQe2VX/KVV5K2tvblsIgtMsQcQNr2R8O1bhmBrjGXOfFEQsp5ZgAvGKUY1NAI4vEDyDbf/auFefMiJns+39GK7Us/ANVUvJP21MTipmdzA0c5tIZL4wJgtGrJNXP//JqKCuAsQutUV8zmiJ/zuih1qHv+0OH3sgQUQMXBO2m+mgSKiSE1zCEwGPofvzGUuthxEmoK9MU5qYcwWmFGgz9tdYvzCswSKxju7XkcjoOmRXBuakMKgW5xUtVgwb2lKOXrm+mXBxNzAkaxDQJXyhyKvQtkohUI7P+nLOE0XovTodd0suK/Y8GkOvQtJiCgPlcizJvbSbCl5cesmMJefFplpQITsNMirNEPHUvBdWeR/5vRZ2ZGrkKaPw066kQXVwSuQfQb0w+2fY2SkXx/UAfBx1Rp6Yzyi/jDNKf/Ot7L9Gpe85/rec+IjYIGkuXUPeKrF1FUk7NusiD6QW+ejBO9tJ+lUpx3jUPw9ir8i2QIM+mu7+456GzyfPpU9TzYaB3DBU1G3aEqK1syQC94ixYCJ/q3herYSrGbD9bBK/FnH+jSefKj5JHfRl47nEMGTWmF/8UmobPq0YrymNA11KmKKCIUX6XGM="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "rroehwZnHir7Pq5L38fJp7aYZ5icoWEFp1eokC0OfdmOojMnRnOpAXox8rpZLvvccahp3m0KqA1eE6lT7T9sExzhAqEnY0pYeis6rwzArDAZ4O1ouse7x2n1GkzWOBEXJ2gL+gkFqunA/uNFCKfQxGw8cLfCAvinUxexP2kPd2/vIyLrHcX60xXneNrU6e0jozi9kr4iHoqzroZQx9Cu3a81/2LdMVYaHrhBAxmrBUV+G3K6nOgfOoZJY7SS7SkOvs9RQNf0vBadaljSsDVxMFHGo5X7u3l/DmPfjNAVdKDL/XxtEUlXWZvFHlWUEB/M5rbN6XPSBYW9L7GzqxJxaUzfK2nghkSZtL/vt+arpjGO49g72Zf8e02x16Ap9aYcCXtMJZDbgbD1fYauHhjpTi2d41kgrFnf2zuFohDm/S3ljVaPsYukjWQMhhV35u0/0gIfeDYZPKTbAzzErUDJw/0xtYtyhleLZ/9yjj1pT3jxv+6GLjKz4wC4ul+eYIp/dq4mwBW+0Fjcsx1G/ZCYUkC3eKwCoe12lQGD1ziA4yD1TL2bUKFO48sCuLQhPPsg7cf6BRtUuZSJfnic1ZD+Es/acun0vsFDg84CfGJ9pGKShbj+bg6BuezlZlzJWikY7O7dydfk4YSQNE5PaA1vgfq2zYW0K/+/4VOwVWbW7MU="

install:
  - mkdir scripts
  - $SBT transferCommonResources
  - scripts/commonSetup

script:
    - set -e

    - $SBT ++$TRAVIS_SCALA_VERSION test

    - |-
      if [ $TRAVIS_PULL_REQUEST == "false" ] && [[ "$TRAVIS_BRANCH" =~ backport/v.*|master ]]; then
        $SBT transferPublishAndTagResources;
        TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/quasar-destination-avalanche';
        bumpInDownstream() { echo $1 > slamdata-destination-avalanche-version; }
        export -f bumpInDownstream
        scripts/bumpDependentProject slamdata slamx bumpInDownstream
      fi

after_success:
  - scripts/checkAndAutoMerge
  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/
